openapi: 3.0.0
info:
  title: Health Check API
  version: 1.0.0
  description: Health check endpoints for the authentication service

components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: "OK"
        timestamp:
          type: string
          format: date-time

paths:
  /health:
    get:
      summary: Health Check
      description: Returns the health status of the service
      operationId: getHealth
      tags:
        - Health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '503':
          description: Service is unhealthy
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/HealthResponse'
                  - type: object
                    properties:
                      message:
                        type: string

